# Site settings
title: techArtJam
email: chad@techartjam.com
description: > # this means to ignore newlines until "baseurl:"
  Chad Moore is a former Technical Art Director in the video games business. Currently he coaches awesome people working in the intersection of art and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: techartjam
github_username:  techartjam

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
